import { Contest } from '../types';

export const DEFAULT_CONTESTS: Contest[] = [
  {
    id: 'breach-the-bug-round-2',
    title: 'Breach the Bug — Round 2',
    tagline: 'Intermediate Code & Logic Debugging Arena',
    description: 'Round 2 of the official Designers Domain Club debugging championship. Diagnose and resolve 5 debugging challenges in C and Python under strict timed conditions.',
    rules: [
      'Each participant gets an individual 45-minute countdown starting upon registration.',
      'The competition comprises 5 debugging challenges with starter code preloaded in C and Python.',
      'Test your solutions with sample test cases or custom inputs before submitting.',
      'Submissions are scored against strict hidden test cases evaluated server-side in isolated sandboxes.',
      'Ranking logic: Total Score (DESC), Solved Count (DESC), Completion Time (ASC).'
    ],
    organization: 'Designers Domain Club',
    designedBy: 'Aegis',
    status: 'active',
    durationMinutes: 45,
    isPublic: true,
    allowRegistration: true,
    questionIds: ['btb2-q1', 'btb2-q2', 'btb2-q3', 'btb2-q4', 'btb2-q5'],
    totalMarks: 50,
    totalQuestions: 5,
    participantCount: 0,
    submissionCount: 0,
    createdAt: Date.now() - 3600 * 1000 * 24,
    updatedAt: Date.now(),
  },
  {
    id: 'breach-the-bug-round-3',
    title: 'Breach the Bug — Round 3',
    tagline: 'Grand Finale: Advanced Algorithmic & Systems Debugging',
    description: 'The decisive championship finale. Solve 8 advanced algorithmic and system debugging challenges in C and Python featuring pointer arithmetic, sliding windows, recursion, dynamic programming, and data structure invariants.',
    rules: [
      'Contest duration: 60 minutes individual countdown timer.',
      '8 advanced debugging challenges covering algorithms, pointer safety, dynamic programming, and data structures.',
      'Submissions are evaluated against comprehensive edge-case suites with partial scoring for test coverage.',
      'Ranking logic: Total Score (DESC), Solved Count (DESC), Completion Time (ASC).'
    ],
    organization: 'Designers Domain Club',
    designedBy: 'Aegis',
    status: 'active',
    durationMinutes: 60,
    isPublic: true,
    allowRegistration: true,
    questionIds: [
      'btb3-q1',
      'btb3-q2',
      'btb3-q3',
      'btb3-q4',
      'btb3-q5',
      'btb3-q6',
      'btb3-q7',
      'btb3-q8',
    ],
    totalMarks: 80,
    totalQuestions: 8,
    participantCount: 0,
    submissionCount: 0,
    createdAt: Date.now() - 3600 * 1000 * 12,
    updatedAt: Date.now(),
  },
];
